title: Joe Cool's Online Biography

email: hello@joecool.com
github_url: https://github.com/joecool
linkedin_url: https://linkedin.com/in/joecool
medium_url: https://medium.com/joecool
twitter_url: https://twitter.com/joecool

exclude: screenshots, LICENSE, README.md
markdown: kramdown
